# This file was generated by project setup for project SDQ.
# As you work on the project, you should add commands to this file so that
# it contains the commands needed to rebuild the whole project from scratch.
# Typically, those will be source() or rmarkdown::render() calls, like below.


source('002_read-data.R')
source('003_check-and-process-data.R')
rmarkdown::render('01_schola-styled-word.Rmd', output_dir = 'reports-output')
rmarkdown::render('02_schola-styled-redoc.Rmd', output_dir = 'reports-output')
rmarkdown::render('99_reproducibility.Rmd', output_dir = 'reports-output')



