# This file was generated by project setup to hold shared variables for project SDQ.
# It is loaded by default by each RMarkdown file created using reschola's templates.
# You should add all variables needed in multiple scripts here.

# Do not add passwords, API keys and other information that should not be made public.

# Store those in .Renviron. usethis::edit_r_environ() opens it for you for editing.
project_title <- "SDQ"
gd_url <- "https://drive.google.com/drive/u/1/folders/1ldKRvF225TFJdI09wLsyL0GaOoneKIds"
